# Generated by Django 5.0.3 on 2024-04-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_label_owner_alter_task_labels_alter_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.label'),
        ),
    ]
